- hosts: all
  become: true
  tasks:
   - name: Log into DockerHub
     docker_login:
      username: phanirudra9
      password: Ganesh143@docker
      email: seshagirikorada764@gmail.com

   - name: Pull image from docker hub
     command: docker pull ganesh764/google:"{{buildNumber}}"

   - name: Stop current running container
     command: docker stop google-c1
     ignore_errors: yes

   - name: Remove stopped container
     command: docker rm google-c1
     ignore_errors: yes

   - name: Run a container from the pulled image
     command: docker run -itd --name google-c1 -p 80:8080 ganesh764/google:"{{buildNumber}}"
