- hosts: all
  become: true
  tasks:
   - name: Simple GET operation
     aws_s3:
       bucket: phani-artifact.in
       object: webapp.war
       dest: /root/webapp.war
       mode: get
   - name: Build  image 
     shell: |
      docker build -t phani9-devops .
      docker run -d --name phani-c1 -p 8080:8080 phani9-devops
     args:
      chdir:/root
