- hosts: all
  become: true
  tasks:
   - name: Simple GET operation
     aws_s3:
       bucket: phani-artifact.in
       object: webapp.war
       dest: /root/webapp.war
       mode: get

   - name: Stop current running container
     command: docker stop phani-c1
     ignore_errors: yes

   - name: Remove stopped container
     command: docker rm phani-c1
     ignore_errors: yes

   - name: Log into DockerHub
     docker_login:
      username: phanirudra9
      password: 9eb876d4@A
      email: lprudra9@gmail.com   
   
   - name: remove docker image
     shell: |
      docker rmi phani9-devops:latest phanirudra9/phani9-devops
      docker rmi phani9-devops:latest
      docker rmi tomcat
     ignore_errors: yes

   - name: Build and tag docker image using war file
     shell: |
      docker build -t phani9-devops /root
      docker tag phani9-devops phanirudra9/phani9-devops
      
   - name: Push image to docker hub
     command: docker push phanirudra9/phani9-devops

   - name: remove docker image
     shell: |
      docker rmi phani9-devops:latest phanirudra9/phani9-devops
      docker rmi tomcat
     ignore_errors: yes

   - name: Pull image from docker hub
     command: docker pull phanirudra9/phani9-devops:latest

   - name: Run a container from the pulled image
     command: docker run -d --name phani-c1 -p 80:8080 phanirudra9/phani9-devops:latest
